[idris2]
url = "https://github.com/buzden/Idris2"
version = "0.6.0"
commit = "5e9ae63d95d690c19c6aa7564939f9dec24872cb"

[custom.all.deptycheck]
type   = "git"
url    = "https://gitlab.ispras.ru/vmver/deptycheck"
commit = "e3e7388ea40f532d63228b2fb9ad275f08855ffa"
ipkg   = "deptycheck.ipkg"

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/buzden/idris2-elab-util"
commit = "e2cd24824d2c215a88d7d160d73a25cc67ca9d28"
ipkg   = "elab-util.ipkg"
